
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIGUALleftMASMENOSleftMULDIVCOMA DIGIT DIV ELSE ID IF IGUAL INT LK LP MAIN MAS MENOS MUL PC PRINT RK RP SUM TEXT\n    ini : main\n        | vacio\n    \n    main : MAIN LK sentence RK\n    \n    vacio :\n    \n    sentence : single_stmt\n            | if_stmt\n            | single_stmt sentence\n            | if_stmt sentence\n    \n    single_stmt : int_decl\n                | single_op\n                | print\n    \n      int_decl : INT ID IGUAL term PC\n    \n    term : DIGIT\n        | ID\n        | sum_function operator_term\n    \n    operator_term : operator_term operator term\n                  | vacio\n    \n    sum_function : SUM LP ID RP\n    \n    operator : MAS\n            | MENOS\n            | MUL\n            | DIV\n    \n    single_op : ID IGUAL term PC\n    \n    print : PRINT LP ID RP PC\n          | PRINT LP TEXT RP PC\n    \n    if_stmt : IF ID LK single_stmt RK\n            | IF ID LK single_stmt RK ELSE LK single_stmt RK\n    '
    
_lr_action_items = {'MAIN':([0,],[4,]),'$end':([0,1,2,3,16,],[-4,0,-1,-2,-3,]),'LK':([4,19,50,],[5,23,53,]),'IF':([5,7,8,9,10,11,33,40,47,48,49,55,],[12,12,12,-9,-10,-11,-23,-26,-12,-24,-25,-27,]),'INT':([5,7,8,9,10,11,23,33,40,47,48,49,53,55,],[14,14,14,-9,-10,-11,14,-23,-26,-12,-24,-25,14,-27,]),'ID':([5,7,8,9,10,11,12,14,20,22,23,29,33,36,40,41,42,43,44,45,47,48,49,53,55,],[13,13,13,-9,-10,-11,19,21,24,30,13,24,-23,46,-26,24,-19,-20,-21,-22,-12,-24,-25,13,-27,]),'PRINT':([5,7,8,9,10,11,23,33,40,47,48,49,53,55,],[15,15,15,-9,-10,-11,15,-23,-26,-12,-24,-25,15,-27,]),'RK':([6,7,8,9,10,11,17,18,32,33,40,47,48,49,54,55,],[16,-5,-6,-9,-10,-11,-7,-8,40,-23,-26,-12,-24,-25,55,-27,]),'IGUAL':([13,21,],[20,29,]),'LP':([15,28,],[22,36,]),'DIGIT':([20,29,41,42,43,44,45,],[26,26,26,-19,-20,-21,-22,]),'SUM':([20,29,41,42,43,44,45,],[28,28,28,-19,-20,-21,-22,]),'TEXT':([22,],[31,]),'PC':([24,25,26,27,34,35,37,38,39,51,52,],[-14,33,-13,-4,-15,-17,47,48,49,-16,-18,]),'MAS':([24,26,27,34,35,51,52,],[-14,-13,-4,42,-17,-16,-18,]),'MENOS':([24,26,27,34,35,51,52,],[-14,-13,-4,43,-17,-16,-18,]),'MUL':([24,26,27,34,35,51,52,],[-14,-13,-4,44,-17,-16,-18,]),'DIV':([24,26,27,34,35,51,52,],[-14,-13,-4,45,-17,-16,-18,]),'RP':([30,31,46,],[38,39,52,]),'ELSE':([40,],[50,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ini':([0,],[1,]),'main':([0,],[2,]),'vacio':([0,27,],[3,35,]),'sentence':([5,7,8,],[6,17,18,]),'single_stmt':([5,7,8,23,53,],[7,7,7,32,54,]),'if_stmt':([5,7,8,],[8,8,8,]),'int_decl':([5,7,8,23,53,],[9,9,9,9,9,]),'single_op':([5,7,8,23,53,],[10,10,10,10,10,]),'print':([5,7,8,23,53,],[11,11,11,11,11,]),'term':([20,29,41,],[25,37,51,]),'sum_function':([20,29,41,],[27,27,27,]),'operator_term':([27,],[34,]),'operator':([34,],[41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ini","S'",1,None,None,None),
  ('ini -> main','ini',1,'p_ini','Tuii.py',117),
  ('ini -> vacio','ini',1,'p_ini','Tuii.py',118),
  ('main -> MAIN LK sentence RK','main',4,'p_main','Tuii.py',126),
  ('vacio -> <empty>','vacio',0,'p_vacio','Tuii.py',133),
  ('sentence -> single_stmt','sentence',1,'p_sentence','Tuii.py',141),
  ('sentence -> if_stmt','sentence',1,'p_sentence','Tuii.py',142),
  ('sentence -> single_stmt sentence','sentence',2,'p_sentence','Tuii.py',143),
  ('sentence -> if_stmt sentence','sentence',2,'p_sentence','Tuii.py',144),
  ('single_stmt -> int_decl','single_stmt',1,'p_single_stmt','Tuii.py',155),
  ('single_stmt -> single_op','single_stmt',1,'p_single_stmt','Tuii.py',156),
  ('single_stmt -> print','single_stmt',1,'p_single_stmt','Tuii.py',157),
  ('int_decl -> INT ID IGUAL term PC','int_decl',5,'p_int_decl','Tuii.py',165),
  ('term -> DIGIT','term',1,'p_term','Tuii.py',173),
  ('term -> ID','term',1,'p_term','Tuii.py',174),
  ('term -> sum_function operator_term','term',2,'p_term','Tuii.py',175),
  ('operator_term -> operator_term operator term','operator_term',3,'p_operator_term','Tuii.py',185),
  ('operator_term -> vacio','operator_term',1,'p_operator_term','Tuii.py',186),
  ('sum_function -> SUM LP ID RP','sum_function',4,'p_sum_function','Tuii.py',197),
  ('operator -> MAS','operator',1,'p_operator','Tuii.py',205),
  ('operator -> MENOS','operator',1,'p_operator','Tuii.py',206),
  ('operator -> MUL','operator',1,'p_operator','Tuii.py',207),
  ('operator -> DIV','operator',1,'p_operator','Tuii.py',208),
  ('single_op -> ID IGUAL term PC','single_op',4,'p_single_op','Tuii.py',216),
  ('print -> PRINT LP ID RP PC','print',5,'p_print','Tuii.py',224),
  ('print -> PRINT LP TEXT RP PC','print',5,'p_print','Tuii.py',225),
  ('if_stmt -> IF ID LK single_stmt RK','if_stmt',5,'p_if_stmt','Tuii.py',233),
  ('if_stmt -> IF ID LK single_stmt RK ELSE LK single_stmt RK','if_stmt',9,'p_if_stmt','Tuii.py',234),
]
