
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIGUALleftMASMENOSleftMULDIVCOMA DIGIT DIV ELSE ID IF IGUAL INT LK LP MAIN MAS MENOS MUL PC PRINT RK RP SUM TEXT\n    ini : main\n        | vacio\n    \n    main : MAIN LK sentence RK\n    \n    vacio :\n    \n    sentence : single_stmt\n            | if_stmt\n            | single_stmt sentence\n            | if_stmt sentence\n    \n    single_stmt : int_decl\n                | single_op\n                | print\n    \n      int_decl : INT ID IGUAL term PC\n    \n    term : DIGIT operator_term\n        | ID operator_term\n        | sum_function operator_term\n    \n    operator_term : operator_term operator term\n                  | vacio\n    \n    sum_function : SUM LP ID RP\n    \n    operator : MAS\n            | MENOS\n            | MUL\n            | DIV\n    \n    single_op : ID IGUAL term PC\n    \n    print : PRINT LP ID RP PC\n          | PRINT LP TEXT RP PC\n    \n    if_stmt : IF ID LK single_stmt RK\n            | IF ID LK single_stmt RK ELSE LK single_stmt RK\n    '
    
_lr_action_items = {'MAIN':([0,],[4,]),'$end':([0,1,2,3,16,],[-4,0,-1,-2,-3,]),'LK':([4,19,52,],[5,23,55,]),'IF':([5,7,8,9,10,11,35,42,49,50,51,57,],[12,12,12,-9,-10,-11,-23,-26,-12,-24,-25,-27,]),'INT':([5,7,8,9,10,11,23,35,42,49,50,51,55,57,],[14,14,14,-9,-10,-11,14,-23,-26,-12,-24,-25,14,-27,]),'ID':([5,7,8,9,10,11,12,14,20,22,23,29,35,38,42,43,44,45,46,47,49,50,51,55,57,],[13,13,13,-9,-10,-11,19,21,24,30,13,24,-23,48,-26,24,-19,-20,-21,-22,-12,-24,-25,13,-27,]),'PRINT':([5,7,8,9,10,11,23,35,42,49,50,51,55,57,],[15,15,15,-9,-10,-11,15,-23,-26,-12,-24,-25,15,-27,]),'RK':([6,7,8,9,10,11,17,18,32,35,42,49,50,51,56,57,],[16,-5,-6,-9,-10,-11,-7,-8,42,-23,-26,-12,-24,-25,57,-27,]),'IGUAL':([13,21,],[20,29,]),'LP':([15,28,],[22,38,]),'DIGIT':([20,29,43,44,45,46,47,],[26,26,26,-19,-20,-21,-22,]),'SUM':([20,29,43,44,45,46,47,],[28,28,28,-19,-20,-21,-22,]),'TEXT':([22,],[31,]),'MAS':([24,26,27,33,34,36,37,53,54,],[-4,-4,-4,44,-17,44,44,-16,-18,]),'MENOS':([24,26,27,33,34,36,37,53,54,],[-4,-4,-4,45,-17,45,45,-16,-18,]),'MUL':([24,26,27,33,34,36,37,53,54,],[-4,-4,-4,46,-17,46,46,-16,-18,]),'DIV':([24,26,27,33,34,36,37,53,54,],[-4,-4,-4,47,-17,47,47,-16,-18,]),'PC':([24,25,26,27,33,34,36,37,39,40,41,53,54,],[-4,35,-4,-4,-14,-17,-13,-15,49,50,51,-16,-18,]),'RP':([30,31,48,],[40,41,54,]),'ELSE':([42,],[52,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ini':([0,],[1,]),'main':([0,],[2,]),'vacio':([0,24,26,27,],[3,34,34,34,]),'sentence':([5,7,8,],[6,17,18,]),'single_stmt':([5,7,8,23,55,],[7,7,7,32,56,]),'if_stmt':([5,7,8,],[8,8,8,]),'int_decl':([5,7,8,23,55,],[9,9,9,9,9,]),'single_op':([5,7,8,23,55,],[10,10,10,10,10,]),'print':([5,7,8,23,55,],[11,11,11,11,11,]),'term':([20,29,43,],[25,39,53,]),'sum_function':([20,29,43,],[27,27,27,]),'operator_term':([24,26,27,],[33,36,37,]),'operator':([33,36,37,],[43,43,43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ini","S'",1,None,None,None),
  ('ini -> main','ini',1,'p_ini','Tuii.py',118),
  ('ini -> vacio','ini',1,'p_ini','Tuii.py',119),
  ('main -> MAIN LK sentence RK','main',4,'p_main','Tuii.py',127),
  ('vacio -> <empty>','vacio',0,'p_vacio','Tuii.py',134),
  ('sentence -> single_stmt','sentence',1,'p_sentence','Tuii.py',142),
  ('sentence -> if_stmt','sentence',1,'p_sentence','Tuii.py',143),
  ('sentence -> single_stmt sentence','sentence',2,'p_sentence','Tuii.py',144),
  ('sentence -> if_stmt sentence','sentence',2,'p_sentence','Tuii.py',145),
  ('single_stmt -> int_decl','single_stmt',1,'p_single_stmt','Tuii.py',156),
  ('single_stmt -> single_op','single_stmt',1,'p_single_stmt','Tuii.py',157),
  ('single_stmt -> print','single_stmt',1,'p_single_stmt','Tuii.py',158),
  ('int_decl -> INT ID IGUAL term PC','int_decl',5,'p_int_decl','Tuii.py',166),
  ('term -> DIGIT operator_term','term',2,'p_term','Tuii.py',174),
  ('term -> ID operator_term','term',2,'p_term','Tuii.py',175),
  ('term -> sum_function operator_term','term',2,'p_term','Tuii.py',176),
  ('operator_term -> operator_term operator term','operator_term',3,'p_operator_term','Tuii.py',188),
  ('operator_term -> vacio','operator_term',1,'p_operator_term','Tuii.py',189),
  ('sum_function -> SUM LP ID RP','sum_function',4,'p_sum_function','Tuii.py',200),
  ('operator -> MAS','operator',1,'p_operator','Tuii.py',208),
  ('operator -> MENOS','operator',1,'p_operator','Tuii.py',209),
  ('operator -> MUL','operator',1,'p_operator','Tuii.py',210),
  ('operator -> DIV','operator',1,'p_operator','Tuii.py',211),
  ('single_op -> ID IGUAL term PC','single_op',4,'p_single_op','Tuii.py',219),
  ('print -> PRINT LP ID RP PC','print',5,'p_print','Tuii.py',227),
  ('print -> PRINT LP TEXT RP PC','print',5,'p_print','Tuii.py',228),
  ('if_stmt -> IF ID LK single_stmt RK','if_stmt',5,'p_if_stmt','Tuii.py',236),
  ('if_stmt -> IF ID LK single_stmt RK ELSE LK single_stmt RK','if_stmt',9,'p_if_stmt','Tuii.py',237),
]
